steps:

- name: 'gcr.io/kaniko-project/executor:latest'
  id: BuildImage
  args:
    - --destination=gcr.io/$PROJECT_ID/gcloud-ci
    - --cache=true

- name: 'gcr.io/$PROJECT_ID/gcloud-ci'
  id: ListComponents
  waitFor:
  - BuildImage

#images: ['gcr.io/$PROJECT_ID/gcloud-ci']
